=head1 Posemo -- PostgreSQL Secure Monitoring

Posemo is a open source PostgreSQL monitoring backend system, which can
collect a lot of PostgreSQL internals in a secure way without superuser
access.

For an overview, see the README.md in the main directory.


=head2 User manuals

* L<Posemo::Manual::UserConfig|Users Guide to the config file>


=head2 Developer manuals

  * L<Posemo::Manual::CheckModules|How to write check Modules>
  * L<Posemo::Manual::OutputModules|How to write a frontend connector / outout modules>
  * L<Posemo::Manual::StyleguideCoding Styleguide>



=cut
