=head1 Posemo -- PostgreSQL Secure Monitoring

Posemo is a open source PostgreSQL monitoring backend system, which can
collect a lot of PostgreSQL internals in a secure way without superuser
access.

For an overview, see the README.md in the main directory.


=head2 User manuals

* L<Users Guide to the config file|Posemo/Manual/UserConfig.pod>


=head2 Developer manuals

=over 4

=item *

L<Posemo/Manual/CheckModules.pod|How to write check Modules>

=item *

L<Posemo/Manual/OutputModules.pod|How to write a frontend connector / outout modules>

=item *

L<Posemo/Manual/Styleguide.pod|Coding Styleguide>

=back


=cut
