#!/usr/bin/env python                                                    

#
# Proof of concept for new Posemo check for check_mk
#

#
# Remarks about check_ml guidelines
# According to https://mathias-kettner.de/cms_dev_guidelines.html, a check 
# must return values with yield, when there are multiple values.
# Here it returns everything with return to avoid an extra loop, but it 
# may be easy to change this.
# 
# This agent plugin needs JSON, because it decodes JSON from Posemo.
# It may be possible to use an other format; but this is the 
# most flexible at the moment. 
#


# 
# parse_posemo
# Parser function. This parses the output from Posemo (CheckMK output module) and
# returns a data structure (Python dictionary) for the other functions.
#
# We get our result as JSON data, because this is most flexible and readable!
# This parser joins all lines and decodes the JSON.
#
# Because check_mk already splittet every line by whitespace, we have to join it again! 
#

import json

import pprint

def parse_posemo(info):
    json_data = ""
    for line in info:
        json_data += " ".join(line)
    parsed = json.loads(json_data.decode('utf-8'))
    
    # Test ....
    # pprint.pprint(check_info)
    # pprint.pprint(graph_info)        # klappt das? dann kann ich die Sachen doch auch hier befüllen?
    
    # this will not work ... 
    # metric_info.merge(parsed["check_mk_metric_info"])
    # graph_info.merge(parsed["check_mk_graph_info"])
    # 
    return parsed


# 
# inventory_posemo
# 
# In:
#   parsed
#     Already parsed data structure from Posemo
#     In the key check_mk_inventory everything is ready
#
# Return value: 
# List of ..........
#

def inventory_posemo (parsed):
    return parsed["check_mk_inventory"]


# 
# check_posemo
# 
# In:
#   item
#     ...
#   params
#     ...
#   parsed
#     Already parsed data structure from Posemo
#     In the key check_mk_perfdata everything is ready to use
#
# Return value: 
# List of ..........
#

def check_posemo(item, params, parsed):
    return parsed["check_mk_data"]


#
# The following check_info dictionary entry defines, which functions should be called for what task
#

check_info["posemo"] =  {
    "inventory_function"      : inventory_posemo,
    "check_function"          : check_posemo,
    "parse_function"          : parse_posemo,
    "service_description"     : "PostgreSQL %s",        # the source of %s are the inventory services?
    "has_perfdata"            : True,
}


