=head1 Posemo User Manual: Configuration

This manual is about configuring Posemo.


=head2 Overview

...

Usually use Apache style config.

...


=head2 Example

   #
   # Test / Example config file
   #

   global_id = "This is only a test"

   hosts = database.internal.project.tld

   user      = monitoring                      # Monitoring user (unprivileged)
   passwd    = default-blah                    # Password for this user; default: empty
   schema    = public                          # SQL schema name for our tests; default: posemo
   database  = monitoring                      # Name of monitoring DB
   port      = 54321                           # Port number for server to monitor


   <Check Alive>
     Enabled false
   </Check>

   <Check Writeable>
     Timeout 5000
   </Check>


   #
   # or more complex definition with host groups
   #
   # Host group Elephant contains 4 hosts, all with the same config
   # 

   <HostGroup Elephant>
     # NO Order, takes default 0!
     Hosts = loc1_db1 loc1_db2 loc2_db1 loc2_db2 # Short version for hosts, all with default parameters from here or above

     <Check Writeable>
       Enabled true
       Timeout 100                               # timeout 100 ms  (internal parameter from check)
     </Check>
     
   </HostGroup>

   #
   # Host group Mammut contains 2 hosts, all with different config (here: port)
   # 

   <HostGroup Mammut>
     Order = 20

     <Check Trunk>
       Timeout 123
     </Check>
     
     <Hosts>
       hosts = loc1_db1
       port  = 5433
       # ...
     </Hosts>
     <Hosts>
       hosts = loc1_db2
       port  = 5434
       <Check Trunk>
         Timeout 456
       </Check>
       # ....
     </Hosts>
   </HostGroup>

   <HostGroup SingleWithName>
     Order 30
     Hosts = 123.45.67.89
     Name  = my_db_host_name

     <Check Writeable>
       Enabled true
       Timeout 999
     </Check>
     
   </HostGroup>


   <HostGroup MultiWithName>
     Order 40
     Hosts = 1.1.1.1=master_server 2.2.2.2=slave_server
   </HostGroup>


   #
   # Host group ApplicationTests contains 2 hosts,
   # All default tests are disabled, only some specific application tests are enabed on 
   # selected hosts
   # 

   <HostGroup ApplicationTests>                  # An example group for specific / custom application checks

     Order   99999                               # run late
     Enabled false                               # don't run the standard tests: Disable all
     
     <Hosts>
       Hosts   db_lion
       Schema posemo_monitoring                  # our functions are installed in this schema: they should not interfere with application
       <Check ApplicationLion>
         Enabled true                            # enable selectively the check for this application
       </Check>
     </Hosts>
     
     <Hosts>
       hosts db_tiger db_snowtiger               # e.g. two servers with Application Tiger
       Schema posemo_monitoring                  # our functions are installed in this schema: they should not interfere with application
       <Check ApplicationTiger>
         Enabled        true                     # only enable the check for this application
         critical_level 1000                     # set custom critical level, overwrites checks default
       </Check>
     </Hosts>


   </HostGroup>








=head2 Description ....



TODO





=cut
